{
  # Import all your configuration modules here
  imports = [
    ./options.nix
    ./keymaps.nix
    ./bufferline.nix
    ./bufdelete.nix
    ./neo-tree.nix
    ./lualine.nix
    ./dashboard.nix
    ./telescope.nix
    ./todo-comments.nix
    ./which-key.nix
    ./cmp.nix
    ./treesitter.nix
    ./notify.nix
    ./indent-blankline.nix
    ./gitsigns.nix
    ./noice.nix
    ./lsp.nix
    ./neoclip.nix
    ./trouble.nix
    ./sleuth.nix
    ./barbecue.nix
    ./toggleterm.nix
    ./undotree.nix
    ./autopairs.nix 
    ./transparent.nix
    ./web-devicons.nix
    ./code-actions.nix
    ./presence.nix
  ];
}
